Repository kh21rul/FastVoting, pull requests merged in 2022-06, with the labels that each got.

#2 Fix font-awesome script path
  resources/views/layouts/app.blade.php
Labels: bug

#4 Update `Voters` page & Initialize edit event feature
  app/Http/Controllers/EventController.php
  resources/views/pages/event-detail.blade.php
  resources/views/pages/event-edit.blade.php
  routes/web.php
Labels: enhancement

#10 Vote feature
  app/Http/Controllers/VoteController.php
  app/Http/Kernel.php
  app/Http/Middleware/VoteAuthorization.php
  resources/sass/app.scss
  resources/views/emails/voting-invitation.blade.php
  resources/views/layouts/app.blade.php
  resources/views/pages/vote.blade.php
  routes/web.php
Labels: enhancement

#12 Add alert & improve front-end
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  resources/assets/Calendar.png
  resources/assets/iconKunci.png
  resources/assets/iconMail.png
  resources/assets/imgCandidate.png
  resources/sass/app.scss
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/verify.blade.php
  resources/views/components/alert.blade.php
  resources/views/layouts/app.blade.php
  resources/views/pages/about.blade.php
  resources/views/pages/dashboard.blade.php
  resources/views/pages/event-add.blade.php
  resources/views/pages/event-detail.blade.php
  resources/views/pages/home.blade.php
  resources/views/pages/voters.blade.php
Labels: enhancement

#14 Delete event feature
  app/Http/Controllers/EventController.php
  app/Http/Controllers/OptionController.php
  app/Models/Event.php
  app/Models/Option.php
  app/Traits/Uuids.php
Labels: enhancement

#16 Bump guzzlehttp/guzzle from 7.4.4 to 7.4.5
  composer.lock
Labels: bug, dependencies

#18 Use Trix Editor for event description
  app/Http/Requests/EventModifyRequest.php
  app/Http/Requests/OptionPostRequest.php
  app/Traits/TrixEditorValidation.php
  resources/views/pages/dashboard.blade.php
  resources/views/pages/event-add.blade.php
  resources/views/pages/event-detail.blade.php
  resources/views/pages/event-edit.blade.php
  resources/views/pages/option-edit.blade.php
  resources/views/pages/result.blade.php
  resources/views/pages/vote.blade.php
Labels: enhancement

#21 Trix editor improvement
  app/Traits/TrixEditorValidation.php
  composer.lock
  resources/js/app.js
  resources/js/trix.js
  resources/sass/app.scss
  resources/sass/trix.scss
  resources/vendor/trix-editor/trix.min.css
  resources/vendor/trix-editor/trix.min.js
  resources/views/components/trix-editor.blade.php
  resources/views/pages/event-add.blade.php
  resources/views/pages/event-edit.blade.php
  resources/views/pages/option-add.blade.php
  resources/views/pages/option-edit.blade.php
Labels: code improvement, feature improvement

#22 Dashboard admin
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/EventController.php
  app/Http/Controllers/OptionController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/VoterController.php
  app/Http/Middleware/IsEventEditable.php
  app/Models/Event.php
  app/Models/User.php
  app/Policies/EventPolicy.php
  app/Policies/OptionPolicy.php
  app/Policies/UserPolicy.php
  app/Policies/VoterPolicy.php
  app/Providers/AuthServiceProvider.php
  resources/sass/app.scss
  resources/views/pages/dashboard-admin.blade.php
  resources/views/pages/dashboard.blade.php
  resources/views/pages/event-detail.blade.php
  resources/views/pages/event-edit.blade.php
  resources/views/pages/option-add.blade.php
  resources/views/pages/option-edit.blade.php
  resources/views/pages/user-detail.blade.php
  resources/views/pages/voters.blade.php
  routes/web.php
Labels: enhancement, code improvement, feature improvement, fixed
